---

- hosts: myhosts
  name:  config NTP 
  gather_facts: False

  tasks:

  # Config NTP function as below:
  #
  # 1,"ServiceEnabled": ServiceEnabled, true/false
  # 2,"AlternateNtpServer": AlternateNtpServer, ip/domain name
  # 3,"PreferredNtpServer": PreferredNtpServer, ip/domain name
  # 4,"ServerAuthenticationEnabled": ServerAuthenticationEnabled, true/false
  # 5,"NtpAddressOrigin": NtpAddressOrigin, IPv4/IPv6/Static
  # 6,"MinPollingInterval": MinValue, 3~17 and less than MaxValue
  # 7,"MaxPollingInterval": MaxValue, 3~17 and bigger than MinValue
  # 

  - name: config bmc ntp
    local_action: >
       ibmc category=ConfigNTP command='/etc/ansible/ansible_ibmc/configFile/ntpCfg/ntp.ini' ibmcip={{ ibmcip }}
       ibmcuser={{ ibmcuser }} ibmcpswd={{ ibmcpswd }}
