---

- hosts: myhosts
  name: update firm ware
  gather_facts: no


  tasks:


  - name: update frimware 
    local_action: >
       ibmc category='GetFwInfo' command='' ibmcip={{ ibmcip }}
       ibmcuser={{ ibmcuser }} ibmcpswd={{ ibmcpswd }}

