# Don't call this playbook directly. This playbook is called from inventory.yml
---

  - local_action: shell echo "" >> {{outfile}}.csv

  - local_action: shell echo -n "Host,IP," >> {{csvfile}}
    run_once: true  # task runs only once

  - name: Add header row to system information CSV file
    local_action: shell echo -n "{{item}}," >> {{csvfile}}
    run_once: true
    with_items: "{{inventory_items}}"

  - local_action: shell echo "" >> {{csvfile}}
    run_once: true

  - name: Combine all host outputs to one CSV file
    local_action: shell cat {{outfile}}.csv >> {{csvfile}}

  - name: Remove temporary results file
    local_action: file path={{rootdir}}/{{host}} state=absent
