---

- hosts: myhosts
  name: iBMC Manage System Power
  gather_facts: False

  # Commands available:
  #   PowerOn		Turn system power on
  #   PowerOff		Turn system power off, please confirm it again before run the command!
  #   ForceRestart	Reset OS gracefully, is invalid for server in power-off state
  #   GracefulShutdown	Shutdown OS gracefully
  #   ForcePowerCycle	Forcibly power off and then power on
  #   Nmi	        generate a non-maskable interrupt only when the OS is abnormal

  tasks:

  # Except for PowerSate, tasks are mutually exclusive, do only one at a time

  - name: Power Manage
    local_action: >
       ibmc category=Power command=PowerOn ibmcip={{ ibmcip }}
       ibmcuser={{ ibmcuser }} ibmcpswd={{ ibmcpswd }}

