---

- hosts: myhosts
  name: update firmware
  gather_facts: no


  tasks:
  # only support to upgrade iBMC/BIOS/CPLD firmware
  - name: update frimware 
    local_action: >
       ibmc category=UpdateFW command='nfs://192.168.2.241/NFSshare/1288HV5260.hpm' ibmcip={{ ibmcip }}
       ibmcuser={{ ibmcuser }} ibmcpswd={{ ibmcpswd }}

