---
- hosts: myhosts
  connection: local
  name: create raid
  gather_facts: False

# storage_id: ID of the storage resource. Format: RAIDStorage+Controller_ID
# capacity_mbyte: Volume capacity, must be an integer, the size unit is MB. It is an optional parameter
# stripe_size: Stripe size of a volume, must be an integer. It is an optional parameter. Available values: 65536, 131072, 262144, 524288, 1048576
# cachecade_flag: Whether it is a CacheCade volume. It is an optional parameter, Available values: True, False
# drives: Member disk list number. It is a mandatory parameter. Format: "1,2,.,N"
# volume_raid_level: RAID level of the volume. It is a mandatory parameter. Available values: RAID0, RAID1, RAID5, RAID6, RAID10, RAID50, RAID60
# volume_name: Volume name. It is an optional parameter. A string of up to 15 bytes. Value range: ASCII code corresponding to 0x20 to 0x7E
# df_read_policy: Default read policy of the volume. It is an optional parameter. Available values: NoReadAhead, ReadAhead
# df_write_policy: Default write policy of the volume. It is an optional parameter. Available values: WriteThrough, WriteBackWithBBU, WriteBack
# df_cache_policy: Default cache policy of the volume. It is an optional parameter. Available values: CachedIO, DirectIO
# span_num: Number of spans of the volume, must be an integer. It is an optional parameter
  # 1.Set this parameter to 1 when creating a RAID0, RAID1, RAID5, or RAID6 array.
  # 2.Set this parameter to a value from 2 to 8 when creating a RAID10, RAID50, or RAID60 array.
# access_policy: Volume access policy. It is an optional parameter. Available values: ReadWrite, ReadOnly, Blocked
# disk_cache_policy: Cache policy for member disks. It is an optional parameter. Available values: Unchanged, Enabled, Disabled
# init_mode: Volume initialization mode. It is an optional parameter. Available values: UnInit, QuickInit, FullInit


  tasks:
  - name: create raid
    ibmc_create_raid:
      ibmc_ip: "{{ ibmc_ip }}"
      ibmc_user: "{{ ibmc_user }}"
      ibmc_pswd: "{{ ibmc_pswd }}"
      volumes:
       - storage_id: "RAIDStorage0"
         capacity_mbyte: 1000
         stripe_size: 65536
         cachecade_flag: False
         drives: "0,1"
         volume_raid_level: "RAID0"
         volume_name: "volume_name"
         df_read_policy: "NoReadAhead"
         df_write_policy: "WriteThrough"
         df_cache_policy: "CachedIO"
         span_num: 1
         access_policy: "ReadWrite"
         disk_cache_policy: "Unchanged"
         init_mode: "UnInit"
