---
- hosts: myhosts
  connection: local
  name: delete ibmc account
  gather_facts: False

# delete_account: The iBMC user name to be deleted.

  tasks:
  - name: delete ibmc account
    ibmc_delete_account:
      ibmc_ip: "{{ ibmc_ip }}"
      ibmc_user: "{{ ibmc_user }}"
      ibmc_pswd: "{{ ibmc_pswd }}"
      delete_account: "test"