---
- hosts: myhosts
  connection: local
  name: ibmc deploy esxi 6.5 by sp
  gather_facts: False
#os_img: The os image path ; Format: protocol://Username:Password@IPaddress/Folder/image_file; Available protocol: nfs,cifs,https
#OSType:Os type; Available values:RHEL6U9, RHEL6U10, RHEL7U3 ,RHEL7U4, RHEL7U5, RHEL7U6, CentOS6U9, CentOS6U10, CentOS7U3, CentOS7U4, CentOS7U5, CentOS7U6, ESXi6.0, ESXi6.5, ESXi6.7 
# SLES11SP4, SLES12SP2, SLES12SP3, Ubuntu16.04, Ubuntu16.04.1, Ubuntu16.04.2, Win2016, Win2016 Standard Desktop, Win2016 Standard Core, Win2016 Datacenter Desktop
# Win2016 Datacenter Core, Win2012_R2, Win2012_R2 Standard Desktop, Win2012_R2 Standard Core, Win2012_R2 Datacenter Desktop, Win2012_R2 Datacenter Core
# EulerOSV2SP3
#InstallMode: OS Installation mode;  Available values:Recommended, Customized 
#timezone: Available values: windows Format: (GMT-12:00) International Date Line West; centos,redhat,ubuntu Format:Africa/Abidjan;
# SLES Format: Africa/Abidjan ; Please refer to the installation guide of the OS for more infomation.
#language: Available values: windows Format: en-US; centos,redhat,ubuntu Format:en_US.UTF-8; SlES Format:en_US
# Please refer to the installation guide of the OS for more infomation.
#Keyboard: Available values: Please refer to the installation guide of the OS.
#BootType: Bios boot mode,This parameter is optional; Available values: UEFIBoot, LegacyBoot, SecureBoot
#CDKey: key of the OS Installation, This parameter is optional 
#RootPwd: Root user password, this parameter is mandatory;
# Windows: a sting of at least 6 characters.SUSE: a sting of at least 6 characters. 
# Centos/Redhat/ EulerOS: a sting of at least 6 characters excluding #,$, and space.
# Ubuntu: a sting of at least 8 characters excluding #, $, and space.
# Vmware: a string of 7 to 40 characters. For the ESXi 6.7, the password must consist of letters, digits, and special characters.
# (NOTE: Smart Provisioning supports special characters #, $ and spaces from V119.)     
#HostName: Host Name,This parameter is optional Installation
#CheckFirmware: Whether to verify firmware.This parameter is optional; Available values:True, False
#Partition: Partition information. This parameter is optional. Please refer to the installation guide of the OS
#Software: Software list. This parameter is mandatory.Format:{ "FileName": "iBMA" }
#Autopart: Whether auto-partitioning is supported. Linux/VMware: true Window: false
#MediaType:Type of the media where the OS can be deployed.This parameter is optional; Available values:SANBoot, Disk, USB
#AutoPosition: Whether the installation drive is automatically selected ; Available values:True
#NetCfg: Network config 
  tasks:
  - name: ibmc deploy esxi 6.5 by sp
    ibmc_deploy_os_by_sp:
      ibmc_ip: "{{ ibmc_ip }}"
      ibmc_user: "{{ ibmc_user }}"
      ibmc_pswd: "{{ ibmc_pswd }}"
      os_img: "nfs://172.26.200.11/data/esxi65.iso"
      os_config:
        InstallMode: "Recommended"
        OSType: "ESXi6.5"
        CDKey: ""
        RootPwd: "{{ os_pswd }}"
        HostName: "test"
        Language: "" 
        TimeZone: ""
        Keyboard: ""
        CheckFirmware: False
        Partition: []
        Autopart: True
        AutoPosition: True
        Software: []
        NetCfg:
           - Device:
                Name: "eth10086"
                MAC: "**:**:**:**:**:**"
             IPv4Addresses:
                - Address: "192.168.2.44"
                  SubnetMask: "255.255.0.0"
                  Gateway: "192.168.2.1"
                  AddressOrigin: "Static"
             IPv6Addresses:
                - Address: ""
                  PrefixLength: ""
                  Gateway: ""
                  AddressOrigin: "Static"
             NameServers:
                - DNS: "192.168.2.1"
                - DNS: "192.168.2.2"