---
- hosts: myhosts
  connection: local
  name: get bmc basic info
  gather_facts: False

  tasks:
  - name: get bmc basic info
    ibmc_get_basic_info:
      ibmc_ip: "{{ ibmc_ip }}"
      ibmc_user: "{{ ibmc_user }}"
      ibmc_pswd: "{{ ibmc_pswd }}" 