---
- hosts: myhosts
  connection: local
  name: get boot device
  gather_facts: False

  tasks:
  - name: get boot device
    ibmc_get_boot_device:
      ibmc_ip: "{{ ibmc_ip }}"
      ibmc_user: "{{ ibmc_user }}"
      ibmc_pswd: "{{ ibmc_pswd }}"

