---
- hosts: myhosts
  connection: local
  name: get ntp
  gather_facts: False

  tasks:
  - name: get ntp
    ibmc_get_ntp:
      ibmc_ip: "{{ ibmc_ip }}"
      ibmc_user: "{{ ibmc_user }}"
      ibmc_pswd: "{{ ibmc_pswd }}"

