---
- hosts: myhosts
  connection: local
  name: get ibmc os power status  
  gather_facts: False

  tasks:
  - name: get ibmc os power status 
    ibmc_get_power_status:
      ibmc_ip: "{{ ibmc_ip }}"
      ibmc_user: "{{ ibmc_user }}"
      ibmc_pswd: "{{ ibmc_pswd }}" 