---
- hosts: myhosts
  connection: local
  name: get snmp trap
  gather_facts: False

  tasks:
  - name: get snmp trap
    ibmc_get_snmp_trap:
      ibmc_ip: "{{ ibmc_ip }}"
      ibmc_user: "{{ ibmc_user }}"
      ibmc_pswd: "{{ ibmc_pswd }}"

