---
- hosts: 127.0.0.1
  connection: local
  name: show Huawei iBMC ansible modules version
  gather_facts: False

  tasks:
  - name: show Huawei iBMC ansible modules version
    ibmc_ansible_show_version: