---
- hosts: myhosts
  connection: local
  name: update outband fw
  gather_facts: False

  tasks:
  - name:   update outband fw
    ibmc_outband_fw_update:
      ibmc_ip: "{{ ibmc_ip }}"
      ibmc_user: "{{ ibmc_user }}"
      ibmc_pswd: "{{ ibmc_pswd }}" 
      image_url: "nfs://172.26.200.11/tmp/package/cpldimage.hpm"
      protocol: "NFS"