---

- hosts: myhosts
  name:  config bmc ip 
  gather_facts: False

  tasks:

  # config ibmc ip including IP address;Subnet mask;Gateway, must be separated by semicolons(;)!

  - name: config bmc ip
    local_action: >
       ibmc category=ConfigBMC command='/etc/ansible/ansible_ibmc/configFile/ibmcCfg/ibmcIPcfg.json' ibmcip={{ ibmcip }}
       ibmcuser={{ ibmcuser }} ibmcpswd={{ ibmcpswd }}
