---

- hosts: myhosts
  name: config snmp trap 
  gather_facts: no

  tasks:


  - name: config snmp
    local_action: >
       ibmc category=CfgSnmpTrap command="/etc/ansible/ansible_ibmc/configFile/snmpCfg/snmpTrap.ini" ibmcip={{ ibmcip }}
       ibmcuser={{ ibmcuser }} ibmcpswd={{ ibmcpswd }} extraparam={{ community }}

