---

- hosts: myhosts
  name: created Account
  gather_facts: no


  tasks:
  # useraccount :A string of 1 to 16 characters.It can contain letters, digits,and special characters (excluding <>&,'"/\%), butcannot contain spaces or start with a number sign (#)
  # newpassword : A string of up to 20 characters.l If password complexity check is enabled for other interfaces, the password must meet password complexity requirements.
  #    If password complexity check is not enabled for other interfaces, there is not restriction on the password.
  # roleid : can be value as follow : Administrator ,Operator, Commonuser, Noaccess,CustomRole1,CustomRole2,CustomRole3,CustomRole4
  - name: create account
    local_action: >
       ibmc category=ManageAccount command="createAccount" useraccount={{ newuser }} newpassword={{ newpswd }} roleid='Administrator' ibmcip={{ ibmcip }}
       ibmcuser={{ ibmcuser }} ibmcpswd={{ ibmcpswd }}

