---

- hosts: myhosts
  name: create raid
  gather_facts: no


  tasks:


  - name: create raid 
    local_action: >
       ibmc category=CfgRaid command='/etc/ansible/ansible_ibmc/configFile/raidCfg/createRaidtmp.json' ibmcip={{ ibmcip }}
       ibmcuser={{ ibmcuser }} ibmcpswd={{ ibmcpswd }}

