---

- hosts: myhosts
  name: delete raid
  gather_facts: no


  tasks:

  - name: delete a raid in a storage
    local_action: >
       ibmc category='DelALD' command='RAIDStorage0/LogicalDrive0' extraparam='' ibmcip={{ ibmcip }}
       ibmcuser={{ ibmcuser }} ibmcpswd={{ ibmcpswd }}
       
  #- name: delete ALL raid  in a storage
  # local_action: >
  #    ibmc category='DelLD' command='RAIDStorage0' extraparam='' ibmcip={{ ibmcip }}
  #    ibmcuser={{ ibmcuser }} ibmcpswd={{ ibmcpswd }}
  #- name: delete ALL raid  in each storage
  # local_action: >
  #    ibmc category='DelLD' command='ALL' extraparam='' ibmcip={{ ibmcip }}
  #    ibmcuser={{ ibmcuser }} ibmcpswd={{ ibmcpswd }}

