---

- hosts: myhosts
  name: modify raid
  gather_facts: no


  tasks:


  - name: modify raid
    local_action: >
       ibmc category=ModifyRaid command='/etc/ansible/ansible_ibmc/configFile/raidCfg/modifyRaid.json' ibmcip={{ ibmcip }}
       ibmcuser={{ ibmcuser }} ibmcpswd={{ ibmcpswd }}

