---

- hosts: myhosts
  name: import or export server profile
  gather_facts: False

# import or export; iBMC and BIOS profile path
# default export profile as /tmp/profile.xml if cli has no paramters#
# export example: 'export;/tmp/profile.xml'
  vars:
   command: 'import;sftp://{{ sftpuser }}:{{ sftppswd }}@192.168.2.156/etc/profile.xml'
  tasks:

  - name: import or export server profile
    local_action: >
       ibmc category=Profile command={{ command }} ibmcip={{ ibmcip }}
       ibmcuser={{ ibmcuser }} ibmcpswd={{ ibmcpswd }}
