---
- hosts: myhosts
  connection: local
  name: get raid
  gather_facts: False

  tasks:
  - name: get raid
    ibmc_get_raid:
      ibmc_ip: "{{ ibmc_ip }}"
      ibmc_user: "{{ ibmc_user }}"
      ibmc_pswd: "{{ ibmc_pswd }}"

